### ISSUE TITLE
Path validation

### ISSUE THREAD

**Issue by sr-murthy** [selectel/pyxs#4] opened 2016-01-08 18:54 UTC
Hi

At the moment there's no method to check whether a given path is a valid Xenstore path - would it be useful to add such a method to `pyxs.helpers`?  A corresponding exception would be added to `pyxs.exceptions`.  I am happy to do that, if you think this is useful.

SM

**Comment by superbobry** [comment] 2016-01-09 21:02
I'm not sure we need a separate exception, since there `InvalidPath` is already there. Otherwise, feel free to submit a PR.

**Comment by sr-murthy** [comment] 2016-01-10 19:03
OK, thanks I might do that - although I am certainly not a Xenstore expert, having used `pyxs` intensively over the last month what I feel would be useful in `pyxs` is to have additional methods for representing directory structures, and some way of making the monitor able to manage the watches created with it, and represent this to the user - at the moment you can create a bunch of watches but it would seem nice for the monitor to keep track of this.

**Comment by superbobry** [comment] 2016-01-10 23:15
> [...] having used `pyxs` intensively over the last month what I feel would be useful in pyxs is to have additional methods for representing directory structures

Can you describe how you use `pyxs` in a few words? I'm curious because until this issue I was pretty sure `pyxs` is useless to the world :)

> and some way of making the monitor able to manage the watches created with it, and represent this to the user - at the moment you can create a bunch of watches but it would seem nice for the monitor to keep track of this.

Do you mean that it'd be convenient to separate directories from the rest of the paths? 

> and some way of making the monitor able to manage the watches created with it, and represent this to the user - at the moment you can create a bunch of watches but it would seem nice for the monitor to keep track of this.

This is easy to implement, yes. Do you have a particular API in mind?

**Comment by sr-murthy** [comment] 2016-01-11 00:25
I can't give too many details, but the basic application I am working on is a Python daemon that sets up watches on certain Xenstore paths that map to GPIO pins that perform certain indicator functions for system features - the pins are output pins and their values must be changed as there are changes to the corresponding Xenstore paths.  The functions these pins perform are independent of each other so in my daemon I implement the watches as daemon threads - each thread uses a separate client and monitor for the path it manages.  The daemon keeps track of all these threads, and this is of course means it can keep track of the watches.  My suggestion is that, as an enhancement to `pyxs`, this could be done by one monitor, perhaps by using threads itself - I found that although you can set up multiple watches using one monitor, the event pipeline cannot be shared, and in you have a situation like this where the watches must be independent of each other each thread has to use a separate monitor.  Does that make any sense? :)

**Comment by superbobry** [comment] 2016-03-02 19:57
Thank you, I didn't realise the problem with multiple monitors until I read your comment. The issue is fixed in the upcoming 0.4.0 release. The `Client` now correctly multiplexes watches to multiple monitors via a single connection.

I would very much appreciate if you could give the `master` version a try and let me know how it works for you.

**Comment by sr-murthy** [comment] 2016-03-02 20:08
Thanks for the update. My particular application was implemented using threads for separate monitors/watches, but I will try to look at the source of your changes, and see whether that could work as well.

**Comment by superbobry** [comment] 2016-05-10 21:17
Closing, since the original issue was fixed in #6.

**Closed by superbobry** 2016-05-10 21:17 UTC

**Comment by sr-murthy** [comment] 2016-05-11 18:43
Thanks - I was unable to test it because after the GPIO project I don't have regular access to the Xen hypervisor at work.  I hope you are able to have it tested by someone else.
